
// DOC'S NFL WAR ROOM
// Connect verified EPA statistics to our dashboard.

(() => {
  "use strict";

  const DATA_URL = "data/epa-2026.json";

  // Match our website's team names to NFL abbreviations.
  const teamCodes = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LA",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS"
  };

  const metrics = [
    ["Offensive EPA / Play", "offensiveEPA"],
    ["Defensive EPA / Play Allowed", "defensiveEPAAllowed"],
    ["Passing EPA / Play", "passingEPA"],
    ["Rushing EPA / Play", "rushingEPA"],
    ["Defensive Passing EPA Allowed", "passingEPAAllowed"],
    ["Defensive Rushing EPA Allowed", "rushingEPAAllowed"]
  ];

  let nflData = null;
  let dataError = false;

  function format(value) {
    return typeof value === "number" &&
      Number.isFinite(value)
      ? value.toFixed(3)
      : "N/A";
  }

  function renderStatistics() {
    const awayName = document.getElementById("away").value;
    const homeName = document.getElementById("home").value;

    if (awayName === homeName) return;

    const body = document.getElementById("epaBody");

    if (!body) return;

    const awayCode = teamCodes[awayName];
    const homeCode = teamCodes[homeName];

    const awayStats = nflData?.teams?.[awayCode];
    const homeStats = nflData?.teams?.[homeCode];

    body.replaceChildren();

    metrics.forEach(([label, key]) => {
      const row = document.createElement("tr");

      const values = [
        label,
        format(awayStats?.[key]),
        format(homeStats?.[key])
      ];

      values.forEach(value => {
        const cell = document.createElement("td");
        cell.textContent = value;
        row.appendChild(cell);
      });

      body.appendChild(row);
    });

    // SOS requires a separate verified calculation.
    const sosRow = document.createElement("tr");

    [
      "Strength of Schedule",
      "Pending",
      "Pending"
    ].forEach(value => {
      const cell = document.createElement("td");
      cell.textContent = value;
      sosRow.appendChild(cell);
    });

    body.appendChild(sosRow);

    let status = document.getElementById("nflDataStatus");

    if (!status) {
      status = document.createElement("p");
      status.id = "nflDataStatus";
      status.className = "note";
      body.closest(".panel").appendChild(status);
    }

    if (dataError) {
      status.textContent =
        "NFL statistics could not be loaded.";
    } else if (!nflData) {
      status.textContent =
        "Loading NFL statistics...";
    } else if (!awayStats || !homeStats) {
      status.textContent =
        "Statistics are unavailable for one or both teams.";
    } else {
      status.textContent =
        "Source: nflverse | Season: " +
        nflData.season +
        " | Updated: " +
        (nflData.updated || "Unknown") +
        " | EPA is not SOS-adjusted.";
    }
  }

  // Connect to the existing Analyze Matchup button.
  const originalAnalyze = window.analyze;

  window.analyze = function () {
    if (typeof originalAnalyze === "function") {
      originalAnalyze();
    }

    renderStatistics();
  };

  // Retrieve the statistics generated by GitHub Actions.
  fetch(DATA_URL, { cache: "no-store" })
    .then(response => {
      if (!response.ok) {
        throw new Error("Unable to retrieve NFL data");
      }

      return response.json();
    })
    .then(data => {
      if (!data || !data.teams) {
        throw new Error("Invalid NFL data");
      }

      nflData = data;
      renderStatistics();
    })
    .catch(error => {
      console.error(error);
      dataError = true;
      renderStatistics();
    });

  renderStatistics();
})();
